### ISSUE TITLE
Release 9.3.2

### ISSUE THREAD

**Issue by khatchad** [ponder-lab/Pydev#7]
- [x] Write instructions on how to bump the version in https://github.com/ponder-lab/Pydev/wiki/How-to-bump-the-version.
- [x] Run the tycho versions plugin to bump to 9.3.2.
- [x] Do any manual changes (but not in Eclipse metadata related to the update site) required.
- [x] Rebuild the update site to host 9.3.2.

**Comment by tatianacv** [comment]
> * [x]  Write instructions on how to bump the version in https://github.com/ponder-lab/Pydev/wiki/How-to-bump-the-version.
> * [x]  Run the tycho versions plugin to bump to 9.3.2.
> * [x]  Do any manual changes (but not in Eclipse metadata related to the update site) required.
> * [x]  Rebuild the update site to host 9.3.2.

**Comment by khatchad** [comment]
Need to test and review that last point before merging.
